Repository AY2425S2-CS2103T-F11-2/tp, pull requests merged in 2025-04, with the labels that each got.

#168 Priority Command Alpha Testing Bugs
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/logic/parser/PriorityCommandParser.java
  src/test/java/seedu/address/logic/commands/PriorityCommandTest.java
  src/test/java/seedu/address/logic/parser/PriorityCommandParserTest.java
Labels: alpha-bug

#167 Fix filter bugs
  preferences.json
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: alpha-bug

#178 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandClassDiagram.puml
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/ClearCommandClassDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/EditCommandClassDiagram.puml
  docs/diagrams/EditCommandSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/test/java/seedu/address/logic/commands/PriorityCommandTest.java
Labels: type.Task

#184 Branch error handling
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: alpha-bug

#188 Update input limits of allergy and test cases
  src/main/java/seedu/address/model/allergy/Allergy.java
  src/test/java/seedu/address/model/allergy/AllergyTest.java
Labels: alpha-bug

#212 Fix name and email bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  preferences.json
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: alpha-bug

#218 Update UG hyperlinks
  docs/UserGuide.md
Labels: alpha-bug

#294 Update name and email validation
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.Bug

#300 Update user guide and fix bugs
  docs/UserGuide.md
  preferences.json
Labels: type.Task

#304 Update UG edit portion
  docs/UserGuide.md
Labels: type.Task

#309 Update UG edit portion
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Email.java
Labels: alpha-bug
